#!/bin/sh

IFACE=$1
ACTION=$2

PUBLIC_IFACE=eth0
if [ "$IFACE" == "$PUBLIC_IFACE" ]; then
	SCRIPT_DIR=/usr/local/sbin
	DNS_SERVER=`nslookup -type=SOA nelson-morfa.org|sed -ne 's/.*origin = \(.*\)/\1/p'`

	case "$ACTION" in
	pre-down)	$SCRIPT_DIR/adauth -i
			$SCRIPT_DIR/gennsupd.pl -s $DNS_SERVER -n $IFACE --noadd | nsupdate -g
			$SCRIPT_DIR/adauth -d
			;;
	up)		$SCRIPT_DIR/adauth -i
			$SCRIPT_DIR/gennsupd.pl -s $DNS_SERVER -n $IFACE | nsupdate -g
			$SCRIPT_DIR/adauth -d
			;;
	dhcp4-change)	$SCRIPT_DIR/adauth -i
			$SCRIPT_DIR/gennsupd.pl -s $DNS_SERVER -n $IFACE --noipv6 --nopurge | nsupdate -g
			$SCRIPT_DIR/adauth -d
			;;
	dhcp6-change)	$SCRIPT_DIR/adauth -i
			$SCRIPT_DIR/gennsupd.pl -s $DNS_SERVER -n $IFACE --noipv4 --nopurge | nsupdate -g
			$SCRIPT_DIR/adauth -d
			;;
	esac
fi
